spring.cassandra.schema-action=create-if-not-exists
spring.cassandra.request.timeout=10s
spring.cassandra.connection.connect-timeout=10s

spring.cassandra.keyspace-name=spring_cassandra
spring.cassandra.local-datacenter=datacenter1

### Properties for Astra DB
# Credentials to Astra DB
#astra.client-id=<CLIENT_ID>
#astra.client-secret=<CLIENT_SECRET>
#astra.application-token=<APP_TOKEN>

# Select an Astra instance
#astra.cloud-region=<DB_REGION>
#astra.database-id=<DB_ID>
#astra.keyspace=spring_cassandra
