services:
  cassandra:
    image: cassandra:3.11.10
    container_name: accessing_data_cassandra
    ports:
      - "9042:9042"
    healthcheck:
      test: ["CMD", "cqlsh", "-u", "cassandra", "-p", "cassandra"]
      interval: 10s
      timeout: 10s
      retries: 10
